### ISSUE TITLE
Adapt to Weaviate standalone

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-helm#28]
## Required Changes

* [x] Previously the `weaviate` container was stateless and did not require local persistence. With standalone requiring disk access, `weaviate` can no longer be a `Deployment`, but needs to be a `StatefulSet`
* [x] Remove `esvector`
* [x] Remove `etcd` (unless still required by the contextionary?)
* [ ] Possibly update contextionary requirements if necessary. Unknown as of today, since this depends on the outcome of semitechnologies/weaviate#1252

**Comment by fefi42** [comment]
The change successfully removed esvector and adds a statefulset for the weaviate pods. Etcd is still used by the contextionary and thus still kept around. 

@etiennedi 
1. So far the `pvc` for the weaviate `statefulSet` is `ReadWriteOnce`. However I assume this must be `ReadWriteMany` once the chart should be horizontally scaleable. As far as I know gke is not supporting `ReadWriteMany` out of the box so we probably still need to keep the indirect dependency to the NFS provisioner or a similar thing.
2. There was a mention to change all configuration to environment variables instead of the weaviate config map? Is that actually desired? If so is everything over env variables settable? So far authentication and authorization is set over the config, they might become a bit cumbersome in a env variable.

**Comment by etiennedi** [comment]
Thanks!

1. `ReadWriteOnce` is fine. When it becomes horizontally scalable in the future, each node/pod will have its own independent disk and Weaviate will - at a software level - take care of replication, etc. Similar to ES or Cassandra. So there won't be multiple pods trying to ever read or write from the same disk.

2. Good point, I'll check and get back to you.
